language: java
sudo: false
install: true

jdk:
  - oraclejdk8

script:
  - ./travis.sh

cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.sonar

notifications:
  email: false
  webhooks:
    - secure: "azdp/Wu6vLgS4XcEx/TwfwpO4kKVnC+V+SN/OhVMrblNeYhT7gNbe8dhBcw70DE8PgcMSg/u5Xs2F2g5lzP/FfUepqvC6vzbq8ksrSZfgWqpXfOQWV2izNfBp57gTrvENl0inKsQrGbHOvgZ2A2GIGNMLPfBma5ezKhZhT8bmQY="
  on_start: always
